### ISSUE TITLE
  import {$,on} from "Sciter" fails.

### ISSUE THREAD

**Issue by 4silvertooth** [c-smile/sciter-js-sdk#12] opened 2020-11-11 12:37 UTC
Check the sqlite db sample, it fails to load with this error.

`warning:DOM: failed to load "/sciter-js-sdk/samples/sqlite/Sciter" file, error=2`

**Comment by jsprog** [comment] 2020-11-11 14:18
Note: I'm sharing this as I it may help fixing internal implementation.

I can confirm about receiving this error followed by:
> Segmentation fault (core dumped)

Not sure what's causing this, but I discovered that the current implementation reports some errors when using `Object.freeze({__proto__: null, ...})`. Bundlers may use this during transformations.

```js
// main.js
import mod from './mod.js' // OK
import { a } from './mod.js' // OK
import * as all from './mod.js' // OK but fails if the bundler converted it and used Object.freeze(__proto__:null...

// mod.js
export default 'module_default'
export const a = 'a-value'
export const b = 'b-value'
```
```js
// After transformation by the bundler
var mod = 'module_default';
const a = 'a-value';
const b = 'b-value';
var mod_all = /*#__PURE__*/Object.freeze({
    __proto__: null,
    'default': mod,
    a: a,
    b: b
});
```

Reported error after running the code generated by the bundler:
> terminate called after throwing an instance of 'qjs::exception'
> Aborted (core dumped)

```js
using @rollup/plugin-replace could fix this
// rollup.config.js
    ....
    ....
    replace({
        delimiters: ['', ''],
	    "__proto__: null,": ""
	})

```

**Comment by c-smile** [comment] 2020-11-11 14:32
> Check the sqlite db sample, it fails to load with this error.
> 
> `warning:DOM: failed to load "/sciter-js-sdk/samples/sqlite/Sciter" file, error=2`

Thanks, fixed by https://github.com/c-smile/sciter-js-sdk/commit/294b71d48a7147ad3bb9bffaecbd9102feb29bc9

I've changed names of internal modules:

`"Sciter"` -> `"@sciter"`
`"System"` -> `"@sys"`
Added `"@env"`

So names of all internal modules start from `@` sign.

**Comment by c-smile** [comment] 2020-11-11 15:49
> ```js
> // After transformation by the bundler
> ```

Not sure why such transformation is required.

**Comment by jsprog** [comment] 2020-11-11 16:48
svelte use a bundler like rollup to build the project and some transformations are applied:
- compiling .svelte files.
- many files -> less files (e.g: 1 javascript file and 1 css file).
- using modern syntax not supported by current and older browsers, and the bundler should take care of the transformation (e.g: private class properties).
- Sciter.js could benefit from the bundler to fix some npm packages to run with it.

I can confirm that the code above runs without issues, but the `__proto__:null,` generated by building the default svelte project (npx degit sveltejs/template my-svelte-project) is crashing the process (Windows and Linux). You also need to `import * as all from './mod'` in your code for this to lands into bundle.js. and I could run the app the moment I removed `__proto__:null,`

Likely, something else is getting affected by `__proto__:null,`, and I'll try to share the details the moment I discover something.

**Comment by c-smile** [comment] 2020-11-11 18:23
> but the `__proto__:null,` generated by building the default svelte project

__proto__ is deprecated and please check:  https://github.com/rollup/rollup/issues/3140

**Comment by jsprog** [comment] 2020-11-11 22:41
@c-smile Thanks for the link. I understand that they're sticking to the deprecated `__proto__` for performance reasons to avoid changing object's prototype after it's creation (it's supported by browsers and some other runtimes including quickjs)

And according to this [https://github.com/rollup/rollup/issues/3096](https://github.com/rollup/rollup/issues/3096), `__proto__: null` is used to set the prototype of namespace objects to `null`.

quickjs has `__proto__` according to these links:
- [https://github.com/bellard/quickjs/blob/master/quickjs-atom.h](https://github.com/bellard/quickjs/blob/master/quickjs-atom.h)
- [https://www.freelists.org/post/quickjs-devel/JS-GetOwnPropertyNames-does-not-include--proto-,1](https://www.freelists.org/post/quickjs-devel/JS-GetOwnPropertyNames-does-not-include--proto-,1)


**What I discovered:**
- The Error only fires when using **`console.log(object_with__proto__null)`**
- The Error won't fire when using `__proto__: undefined` (not tested with browsers)
- You can access the object and assign it, but the moment you `console.log` the second reference, you'll receive the same error.
- You can `console.log` object's properties and `Object.keys(object)`.
- The error has nothing to do with Object.freeze

**Test Code:**
```js
const obj = {
	__proto__: null,
	a: 10,
	b: 20
};

obj; // Ok

obj.a = 11; // Ok
console.log('obj.a:', obj.a); // Ok: property changed to 11

Object.defineProperty(obj, 'a', { value: 12 });
console.log('obj.a:', obj.a); // Ok: property changed to 12

console.log('keys:', Object.keys(obj)); // Ok: not a problem at all

console.log('obj:', obj); // error
console.log(obj); // the same error
// error message:
// terminate called after throwing an instance of 'qjs::exception'
// Aborted (core dumped)

const obj_2 = obj; // Ok
console.log(obj_2); // The same error because it's refering to the same object

const obj_3 = { ...obj }; // Ok
console.log(obj_3); // Ok

```

**Comment by jsprog** [comment] 2020-11-13 12:57
@4silvertooth 
How did you manage to run the sqlite sample?

**Comment by c-smile** [comment] 2020-11-13 14:23
In usciter application that links SQLite statically and sets SQLite as a global namespace object: https://github.com/c-smile/sciter-js-sdk/blob/main/demos/usciter/usciter.cpp#L57

**Comment by jsprog** [comment] 2020-11-13 14:35
I can see the reason now.

**Comment by intrnl** [comment] 2020-11-16 12:19
[Set `freeze` to false](http://rollupjs.org/guide/en/#outputfreeze) in Rollup's output options to remove object freezing for namespaces

**Comment by jsprog** [comment] 2020-11-16 13:29
Thanks for the share. Actually, We didn't had problems with freeze but with `console.log` when used with objects with a null prototype #13. It's already solved.

Anyway, thanks for [https://github.com/intrnl/vite-plugin-svelte](https://github.com/intrnl/vite-plugin-svelte)

**Closed** 2020-11-21 18:03 UTC
